# Generated by Django 3.2.4 on 2023-09-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentblog',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
