# Generated by Django 3.2.4 on 2023-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_recentblog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentblog',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='recentblog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recentblog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recentblog',
            name='month',
        ),
        migrations.RemoveField(
            model_name='recentblog',
            name='ncomm',
        ),
        migrations.AddField(
            model_name='recentblog',
            name='rbday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recentblog',
            name='rbmonth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recentblog',
            name='rbname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recentblog',
            name='rbncomm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recentblog',
            name='rbpic',
            field=models.ImageField(null=True, upload_to='static/rbimage/'),
        ),
    ]
