# Generated by Django 3.2.4 on 2023-09-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230915_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100, null=True)),
                ('tpost', models.CharField(max_length=100, null=True)),
                ('timg', models.ImageField(null=True, upload_to='static/teamimage/')),
                ('theading', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
