# Generated by Django 3.2.4 on 2023-09-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='theading',
            field=models.TextField(null=True),
        ),
    ]
