# Generated by Django 3.2.4 on 2023-09-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_team_theading'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eday', models.IntegerField(null=True)),
                ('eyear', models.IntegerField(null=True)),
                ('emonth', models.CharField(max_length=100, null=True)),
                ('etime', models.TimeField(null=True)),
                ('eplace', models.CharField(max_length=100, null=True)),
                ('ecity', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
