# Generated by Django 3.2.4 on 2023-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='etime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
