# Generated by Django 3.2.4 on 2023-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_event_etime'),
    ]

    operations = [
        migrations.CreateModel(
            name='registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=100, null=True)),
                ('Contact', models.IntegerField(null=True)),
                ('Picture', models.FileField(null=True, upload_to='static/register/')),
                ('Address', models.TextField(null=True)),
            ],
        ),
    ]
