# Generated by Django 3.2.4 on 2023-09-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_registers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='Picture',
            field=models.ImageField(null=True, upload_to='static/register/'),
        ),
    ]
