# Generated by Django 3.2.4 on 2023-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_registers_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='Contact',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
