# Generated by Django 3.2.4 on 2023-09-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_registers_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='epic',
            field=models.ImageField(null=True, upload_to='static/eventimage/'),
        ),
    ]
