# Generated by Django 3.2.4 on 2023-09-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_event_epic'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
