# Generated by Django 3.2.4 on 2023-09-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Contact', models.IntegerField(null=True)),
                ('Address', models.TextField(null=True)),
                ('Message', models.TextField(null=True)),
            ],
        ),
    ]
