# Generated by Django 3.2.4 on 2023-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('exp', models.IntegerField(null=True)),
                ('branch', models.IntegerField(null=True)),
            ],
        ),
    ]
