# Generated by Django 3.2.4 on 2023-09-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='aboutus',
        ),
    ]
