# Generated by Django 3.2.4 on 2023-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_about_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='newevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eday', models.IntegerField(null=True)),
                ('eyear', models.IntegerField(null=True)),
                ('emonth', models.CharField(max_length=100, null=True)),
                ('etime', models.CharField(max_length=100, null=True)),
                ('eplace', models.CharField(max_length=100, null=True)),
                ('ecity', models.CharField(max_length=100, null=True)),
                ('ehead', models.TextField(null=True)),
                ('epic', models.ImageField(null=True, upload_to='static/eventimage/')),
            ],
        ),
    ]
