# Generated by Django 3.2.4 on 2023-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_newevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mob', models.IntegerField(null=True)),
                ('pic', models.ImageField(null=True, upload_to='static/booknow/')),
                ('address', models.TextField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
