# Generated by Django 3.2.4 on 2023-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fft', models.CharField(max_length=100, null=True)),
                ('fst', models.CharField(max_length=100, null=True)),
                ('sft', models.CharField(max_length=100, null=True)),
                ('sst', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.TextField(null=True)),
                ('pic', models.ImageField(null=True, upload_to='static/thoughts/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('prof', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
